// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Color {
    #[prost(float, tag = "1")]
    pub r: f32,
    #[prost(float, tag = "2")]
    pub g: f32,
    #[prost(float, tag = "3")]
    pub b: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vec3 {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub z: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddItemResponse {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineDescriptor {
    #[prost(message, optional, tag = "1")]
    pub v1: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub v2: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "3")]
    pub color: ::core::option::Option<Color>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLineRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub line_descriptor: ::core::option::Option<LineDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriangleDescriptor {
    #[prost(message, optional, tag = "1")]
    pub v1: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub v2: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "3")]
    pub v3: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "4")]
    pub line_color: ::core::option::Option<Color>,
    #[prost(message, optional, tag = "5")]
    pub tri_color: ::core::option::Option<Color>,
    #[prost(enumeration = "CellType", tag = "6")]
    pub cell_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddTriangleRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub triangle_descriptor: ::core::option::Option<TriangleDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaneDescriptor {
    #[prost(message, optional, tag = "1")]
    pub origin: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub x_axis: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "3")]
    pub y_axis: ::core::option::Option<Vec3>,
    #[prost(float, tag = "4")]
    pub x_min: f32,
    #[prost(float, tag = "5")]
    pub x_max: f32,
    #[prost(float, tag = "6")]
    pub y_min: f32,
    #[prost(float, tag = "7")]
    pub y_max: f32,
    #[prost(message, optional, tag = "8")]
    pub line_color: ::core::option::Option<Color>,
    #[prost(message, optional, tag = "9")]
    pub tri_color: ::core::option::Option<Color>,
    #[prost(enumeration = "CellType", tag = "10")]
    pub cell_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddPlaneRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub plane_descriptor: ::core::option::Option<PlaneDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CuboidDescriptor {
    #[prost(message, optional, tag = "1")]
    pub origin: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub x_axis: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "3")]
    pub y_axis: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "4")]
    pub z_axis: ::core::option::Option<Vec3>,
    #[prost(float, tag = "5")]
    pub lenx: f32,
    #[prost(float, tag = "6")]
    pub leny: f32,
    #[prost(float, tag = "7")]
    pub lenz: f32,
    #[prost(message, optional, tag = "8")]
    pub line_color: ::core::option::Option<Color>,
    #[prost(message, optional, tag = "9")]
    pub tri_color: ::core::option::Option<Color>,
    #[prost(enumeration = "CellType", tag = "10")]
    pub cell_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddCuboidRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub cuboid_descriptor: ::core::option::Option<CuboidDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CylinderDescriptor {
    #[prost(message, optional, tag = "1")]
    pub origin: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub axis: ::core::option::Option<Vec3>,
    #[prost(float, tag = "3")]
    pub radius: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
    #[prost(uint32, tag = "5")]
    pub num_sides: u32,
    #[prost(message, optional, tag = "6")]
    pub line_color: ::core::option::Option<Color>,
    #[prost(message, optional, tag = "7")]
    pub tri_color: ::core::option::Option<Color>,
    #[prost(bool, tag = "8")]
    pub open: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddCylinderRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub cylinder_descriptor: ::core::option::Option<CylinderDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SphereDescriptor {
    #[prost(message, optional, tag = "1")]
    pub origin: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub axis: ::core::option::Option<Vec3>,
    #[prost(float, tag = "3")]
    pub radius: f32,
    #[prost(uint32, tag = "4")]
    pub n_lat: u32,
    #[prost(uint32, tag = "5")]
    pub n_long: u32,
    #[prost(message, optional, tag = "6")]
    pub line_color: ::core::option::Option<Color>,
    #[prost(message, optional, tag = "7")]
    pub tri_color: ::core::option::Option<Color>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddSphereRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub sphere_descriptor: ::core::option::Option<SphereDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AxesDescriptor {
    #[prost(message, optional, tag = "1")]
    pub origin: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "2")]
    pub x_axis: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "3")]
    pub y_axis: ::core::option::Option<Vec3>,
    #[prost(message, optional, tag = "4")]
    pub z_axis: ::core::option::Option<Vec3>,
    #[prost(float, tag = "5")]
    pub neg_len: f32,
    #[prost(float, tag = "6")]
    pub pos_len: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddAxesRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub axes_descriptor: ::core::option::Option<AxesDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeshDescriptor {
    #[prost(float, repeated, tag = "1")]
    pub vertices: ::prost::alloc::vec::Vec<f32>,
    #[prost(uint32, repeated, tag = "2")]
    pub indices: ::prost::alloc::vec::Vec<u32>,
    #[prost(enumeration = "CellType", tag = "3")]
    pub cell_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMeshRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub mesh_descriptor: ::core::option::Option<MeshDescriptor>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KillServerRequest {
    #[prost(string, tag = "1")]
    pub client_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KillServerResponse {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CellType {
    None = 0,
    Line = 1,
    Triangle = 2,
}
impl CellType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CellType::None => "NONE",
            CellType::Line => "LINE",
            CellType::Triangle => "TRIANGLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "LINE" => Some(Self::Line),
            "TRIANGLE" => Some(Self::Triangle),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod state_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct StateServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StateServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StateServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StateServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            StateServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn add_line(
            &mut self,
            request: impl tonic::IntoRequest<super::AddLineRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddLine",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddLine"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_triangle(
            &mut self,
            request: impl tonic::IntoRequest<super::AddTriangleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddTriangle",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddTriangle"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_plane(
            &mut self,
            request: impl tonic::IntoRequest<super::AddPlaneRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddPlane",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddPlane"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_cuboid(
            &mut self,
            request: impl tonic::IntoRequest<super::AddCuboidRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddCuboid",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddCuboid"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_cylinder(
            &mut self,
            request: impl tonic::IntoRequest<super::AddCylinderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddCylinder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddCylinder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_sphere(
            &mut self,
            request: impl tonic::IntoRequest<super::AddSphereRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddSphere",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddSphere"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_axes(
            &mut self,
            request: impl tonic::IntoRequest<super::AddAxesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddAxes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddAxes"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_mesh(
            &mut self,
            request: impl tonic::IntoRequest<super::AddMeshRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddItemResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/AddMesh",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "AddMesh"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn clear(
            &mut self,
            request: impl tonic::IntoRequest<super::ClearRequest>,
        ) -> std::result::Result<tonic::Response<super::ClearResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/d3rpc.StateService/clear");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("d3rpc.StateService", "clear"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn kill_server(
            &mut self,
            request: impl tonic::IntoRequest<super::KillServerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::KillServerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/d3rpc.StateService/KillServer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("d3rpc.StateService", "KillServer"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod state_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StateServiceServer.
    #[async_trait]
    pub trait StateService: Send + Sync + 'static {
        async fn add_line(
            &self,
            request: tonic::Request<super::AddLineRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_triangle(
            &self,
            request: tonic::Request<super::AddTriangleRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_plane(
            &self,
            request: tonic::Request<super::AddPlaneRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_cuboid(
            &self,
            request: tonic::Request<super::AddCuboidRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_cylinder(
            &self,
            request: tonic::Request<super::AddCylinderRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_sphere(
            &self,
            request: tonic::Request<super::AddSphereRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_axes(
            &self,
            request: tonic::Request<super::AddAxesRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn add_mesh(
            &self,
            request: tonic::Request<super::AddMeshRequest>,
        ) -> std::result::Result<tonic::Response<super::AddItemResponse>, tonic::Status>;
        async fn clear(
            &self,
            request: tonic::Request<super::ClearRequest>,
        ) -> std::result::Result<tonic::Response<super::ClearResponse>, tonic::Status>;
        async fn kill_server(
            &self,
            request: tonic::Request<super::KillServerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::KillServerResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct StateServiceServer<T: StateService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: StateService> StateServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StateServiceServer<T>
    where
        T: StateService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/d3rpc.StateService/AddLine" => {
                    #[allow(non_camel_case_types)]
                    struct AddLineSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddLineRequest>
                    for AddLineSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddLineRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_line(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddLineSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddTriangle" => {
                    #[allow(non_camel_case_types)]
                    struct AddTriangleSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddTriangleRequest>
                    for AddTriangleSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddTriangleRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_triangle(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddTriangleSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddPlane" => {
                    #[allow(non_camel_case_types)]
                    struct AddPlaneSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddPlaneRequest>
                    for AddPlaneSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddPlaneRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_plane(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddPlaneSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddCuboid" => {
                    #[allow(non_camel_case_types)]
                    struct AddCuboidSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddCuboidRequest>
                    for AddCuboidSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddCuboidRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_cuboid(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddCuboidSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddCylinder" => {
                    #[allow(non_camel_case_types)]
                    struct AddCylinderSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddCylinderRequest>
                    for AddCylinderSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddCylinderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_cylinder(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddCylinderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddSphere" => {
                    #[allow(non_camel_case_types)]
                    struct AddSphereSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddSphereRequest>
                    for AddSphereSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddSphereRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_sphere(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddSphereSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddAxes" => {
                    #[allow(non_camel_case_types)]
                    struct AddAxesSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddAxesRequest>
                    for AddAxesSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddAxesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_axes(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddAxesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/AddMesh" => {
                    #[allow(non_camel_case_types)]
                    struct AddMeshSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::AddMeshRequest>
                    for AddMeshSvc<T> {
                        type Response = super::AddItemResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddMeshRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::add_mesh(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AddMeshSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/clear" => {
                    #[allow(non_camel_case_types)]
                    struct clearSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::ClearRequest> for clearSvc<T> {
                        type Response = super::ClearResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClearRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::clear(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = clearSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/d3rpc.StateService/KillServer" => {
                    #[allow(non_camel_case_types)]
                    struct KillServerSvc<T: StateService>(pub Arc<T>);
                    impl<
                        T: StateService,
                    > tonic::server::UnaryService<super::KillServerRequest>
                    for KillServerSvc<T> {
                        type Response = super::KillServerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::KillServerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StateService>::kill_server(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = KillServerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: StateService> Clone for StateServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: StateService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: StateService> tonic::server::NamedService for StateServiceServer<T> {
        const NAME: &'static str = "d3rpc.StateService";
    }
}
